package com.example.springbootanalyzer.analyzer.model.gradle;

public enum GradleExecutionFailureType {
    NONE,
    INCOMPATIBLE_JAVA_AND_GRADLE,
    EXECUTABLE_NOT_FOUND,
    TIMED_OUT,
    REPORT_NOT_CREATED,
    INIT_SCRIPT_COMPILATION_FAILED,
    SETTINGS_PLUGIN_RESOLUTION_FAILED,
    PLUGIN_RESOLUTION_FAILED,
    DEPENDENCY_RESOLUTION_FAILED,
    BUILD_LOGIC_FAILED,
    TOOLING_API_TRANSPORT_FAILED,
    UNKNOWN
}
