/**
 * Export actions for analysis results.
 *
 * Provides four export modes:
 *  - downloadJson:     Downloads the full AnalyzeRepositoryResponse as a JSON file.
 *  - downloadSarif:    Converts findings to SARIF 2.1.0 and downloads the file.
 *  - downloadMarkdown: Generates a structured Markdown report and downloads the file.
 *  - copySummary:      Writes a plain-text summary of findings to the clipboard.
 */

import type { AnalyzeRepositoryResponse } from '../types';
import { sarifToJson } from './sarif';
import { generateMarkdown } from './markdown';

// ---------------------------------------------------------------------------
// File download helper
// ---------------------------------------------------------------------------

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

function safeFilename(repositoryUrl: string | null | undefined): string {
  if (!repositoryUrl) return 'analysis';
  // Extract "owner-repo" from a GitHub URL
  const match = /github\.com\/([^/]+)\/([^/.]+)/.exec(repositoryUrl);
  if (match) return `${match[1]}-${match[2]}`;
  // Generic: take the last path segment
  const parts = repositoryUrl.replace(/\.git$/, '').split('/');
  return parts[parts.length - 1] || 'analysis';
}

// ---------------------------------------------------------------------------
// Public export actions
// ---------------------------------------------------------------------------

/** Downloads the full analysis result as a pretty-printed JSON file. */
export function downloadJson(result: AnalyzeRepositoryResponse): void {
  const filename = `${safeFilename(result.repositoryUrl)}-analysis.json`;
  downloadBlob(JSON.stringify(result, null, 2), filename, 'application/json');
}

/** Converts findings to SARIF 2.1.0 and downloads the file. */
export function downloadSarif(result: AnalyzeRepositoryResponse): void {
  const filename = `${safeFilename(result.repositoryUrl)}-analysis.sarif`;
  downloadBlob(sarifToJson(result), filename, 'application/sarif+json');
}

/** Generates a structured Markdown report and downloads the file. */
export function downloadMarkdown(result: AnalyzeRepositoryResponse): void {
  const filename = `${safeFilename(result.repositoryUrl)}-analysis.md`;
  downloadBlob(generateMarkdown(result), filename, 'text/markdown');
}

/** Writes a concise plain-text summary to the clipboard. */
export async function copySummary(result: AnalyzeRepositoryResponse): Promise<void> {
  const findings = result.findings ?? [];
  const errors = findings.filter((f) => (f.severity ?? '').toUpperCase() === 'ERROR').length;
  const warnings = findings.filter((f) => (f.severity ?? '').toUpperCase() === 'WARNING').length;
  const infos = findings.filter((f) => (f.severity ?? '').toUpperCase() === 'INFO').length;

  // Top 5 rules by occurrence count
  const ruleCounts = new Map<string, number>();
  for (const f of findings) {
    const rule = f.ruleId ?? f.rule ?? 'unknown';
    ruleCounts.set(rule, (ruleCounts.get(rule) ?? 0) + 1);
  }
  const topRules = [...ruleCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([rule, count]) => `  • ${rule} (${count})`);

  const lines = [
    '# Spring Boot Analyzer — Analysis Summary',
    '',
    `Repository : ${result.repositoryUrl ?? 'unknown'}`,
    `Branch     : ${result.branch ?? 'default branch'}`,
    result.commitSha ? `Commit     : ${result.commitSha}` : null,
    `Build tool : ${result.buildTool ?? 'unknown'}`,
    result.runtimeStackAnalysis?.springBootVersion
      ? `Spring Boot: ${result.runtimeStackAnalysis.springBootVersion}`
      : null,
    '',
    `Findings   : ${findings.length} total`,
    `  Errors   : ${errors}`,
    `  Warnings : ${warnings}`,
    `  Info     : ${infos}`,
    topRules.length > 0 ? '' : null,
    topRules.length > 0 ? 'Top rules:' : null,
    ...topRules,
    '',
    `Generated by Spring Boot Analyzer — https://github.com/RobbanHoglund/spring-boot-analyzer`
  ]
    .filter((l): l is string => l !== null)
    .join('\n');

  await navigator.clipboard.writeText(lines);
}
