server.port=8085
spring.web.resources.static-locations=optional:file:./frontend/dist/,classpath:/static/

management.endpoints.web.exposure.include=health,info

analyzer.workspace-root=${java.io.tmpdir}/spring-boot-analyzer
analyzer.cleanup-after-analysis=true
